<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../public/assets/css/index.css">
    <title>Search for Books</title>
</head>

<body>
    <span class="mt-5">.</span>
    <h1 class='text-center pt-5 mt-5 text-white'>Search for your favorite books...</h1>
    <div id="cover">
        <form method="get" action="/book/search">
            <div class="tb">
                <div class="td"><input type="text" name='book' placeholder="Search" required></div>
                <div class="td" id="s-cover">
                    <button type="submit">
                        <div id="s-circle"></div>
                        <span></span>
                    </button>
                </div>
            </div>
        </form>
    </div>
</body>

</html>